version: '3.9'

services:
  db: # Container de MySQL
    image: mysql:5.7 # FROM mysql:5.7
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: matheus
      MYSQL_PASSWORD: secret

  wordpress:
    depends_on: 
      - db
    image: wordpress:latest
    container_name: wordpress
    ports:
      - "8000:80"
    restart: unless-stopped
    environment: 
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: matheus
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data:
networks:
  wordpress:
