version: '3.9'

services:
  db:
    container_name: mysql
    build: ./mysql/
    image: mysql
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    networks:
      - dockercompose
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/init.sql
  
  flask:
    container_name: python_db
    image: python_db
    depends_on: 
      - db
    build: ./flask/
    ports:
      - "5000:5000"
    restart: always
    networks: 
      - dockercompose

networks:
  dockercompose:
